apiVersion: apps/v1
kind: Deployment
metadata:
  name: debiankk
spec:
  selector:
    matchLabels:
      app: debiankk
  replicas: 1
  template:
    metadata:
      labels:
        app: debiankk
    spec:
      containers:
        - name: debiankk
          image: debiankk/aria2
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1m
              memory: 8Mi
            limits:
              cpu: 300m
              memory: 128Mi
          ports:
              containerPort: 8080
