apiVersion: apps/v1
kind: Deployment
metadata:
  name: gdbot
spec:
  selector:
    matchLabels:
      app: gdbot
  replicas: 1
  template:
    metadata:
      labels:
        app: gdbot
    spec:
      containers:
        - name: gdbot
          image: debiankk/icopy
          imagePullPolicy: Always      
          resources:
            requests:
              cpu: 1m
              memory: 64Mi
            limits:
              cpu: 900m
              memory: 512Mi
          ports:
            - containerPort: 8080               
