apiVersion: apps/v1
kind: Deployment
metadata:
  name: gost
spec:
  selector:
    matchLabels:
      app: gost
  replicas: 1
  template:
    metadata:
      labels:
        app: gost
    spec:
      containers:
        - name: gost
          image: debiankk/gostws
          imagePullPolicy: Always      
          resources:
            requests:
              cpu: 1m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 128Mi
          ports:
            - containerPort: 8080              

