apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssv2
spec:
  selector:
    matchLabels:
      app: ssv2
  replicas: 1
  template:
    metadata:
      labels:
        app: ssv2
    spec:
      containers:
        - name: ssv2
          image: byxiaopeng/ssv2ray
          imagePullPolicy: Always
          ports:
            - containerPort: 8080       
          resources:
            requests:
              cpu: 1m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 128Mi
